### ISSUE TITLE
BlightMagic

### ISSUE THREAD

**Issue by Mistik** [Laboralphy/o876-raycaster-engine#22]
Hey!

I was wondering if you could port BlightMagic to this engine?

**Comment by Laboralphy** [comment]
Hi !

Well, actually yes,I'm working on it.
I have created a new dev branch "multiplayer-server" on github.
And I'm trying to write a new server on it.
The first project I'll create with this new version of the multiplier
server is Blight Magic.

**Comment by Laboralphy** [comment]
Closing issue because the request is being processed.
